#!/bin/sh

# gpg-error-config: simple replacement gpg-error-config that is a shim
# for pkg-config.

# Parse flags
for arg in "$@"; do
  case $arg in
	--cflags)
	  pkg-config --cflags gpg-error
	  ;;
	--libs)
	  pkg-config --libs gpg-error
	  ;;
	--version)
	  pkg-config --modversion gpg-error
	  ;;
	*)
	  echo "Unknown option: $arg" >&2
	  exit 1
	  ;;
  esac
done
