environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
      PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win32-py2.7.exe"

    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "32"
      PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win32-py3.4.exe"

install:
  - ps: (new-object net.webclient).DownloadFile($env:PYWIN32_URL, 'c:\\pywin32.exe')
  - "%PYTHON%/Scripts/easy_install.exe c:\\pywin32.exe"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"


