#!/bin/sh
set -e

unset http_proxy
unset https_proxy

rv=0
for py3 in $(py3versions -s); do
  echo "========= Running tests with $py3 =========="
  if ! $py3 -m unittest dulwich.tests.test_suite; then
    rv=1
  fi
done
exit $rv
